version: "3.8"
services:
  veems:
    build: .   # Use Dockerfile in the current directory
    container_name: veems
    working_dir: /app
    volumes:
      - ./app:/app  # Mount the entire app directory to /app in the container
    ports:
      - "8080:80"
    environment:
      - APACHE_DOCUMENT_ROOT=/app/public
