version: '3.8'

services:
  app:
    build: .
    container_name: veems_app
    working_dir: /app
    volumes:
      - ./app:/app  # Mount the app directory to keep the files synchronized
    ports:
      - "8080:80"   # Map port 8080 on the host to port 80 in the container
